name: Develop Build, Lint and Test

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  prepare:
    name: Lint, Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install node js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run lint command
        run: pnpm run lint

      - name: Run format command
        run: pnpm run format

      - name: Run test command
        run: pnpm run test

      - name: Run build command
        run: pnpm run build

      - name: Success message
        if: success()
        run: echo "🎉 Success"
