name: Develop Deploy

on:
  push:
    branches:
      - develop

jobs:
  prepare:
    name: Lint, Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run test command
        run: pnpm run test

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: prepare

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: e2e

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run build command
        run: pnpm run build
        env:
          VITE_SERVER_API_URL: ${{ secrets.VITE_SERVER_API_URL_DEV }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Sync to S3 using AWS CLI
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }} --delete

      - name: Success message
        if: success()
        run: echo "🎉 Success"
