name: Push to main and deploy to S3

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release + Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm semantic-release

      - name: Setup Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync master with develop
        run: |
          git fetch origin
          git checkout develop
          git pull
          git merge origin/main --ff -m "Merge main to develop"
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run build command
        run: pnpm run build
        env:
          VITE_SERVER_API_URL: ${{ secrets.VITE_SERVER_API_URL_DEV }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Sync to S3 using AWS CLI
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_PROD_BUCKET }} --delete
