name: Push to main

on:
  push:
    branches:
      - main

jobs:
  push:
    name: Push to Main Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm semantic-release

      - name: Setup Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout develop branch
        run: |
          git checkout develop
          git pull

      - name: Merge master into develop
        run: |
          git merge origin/master --ff -m "Auto-merge master to develop"

      - name: Push changes to develop
        run: git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
